models_name:
  - "gemini-1.5-flash"
  - "gemini-2.0-flash"
  - "gemini-1.5-flash-8b"
dotenv_path: src/Data_Discovery/config/model_config/.env
temperature: 0.2
top_p: 0.95
max_output_tokens: 2048
max_retries: 3
